# Generated by Django 2.2.28 on 2022-12-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221209_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
    ]
