# Generated by Django 2.2.28 on 2022-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221210_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='screenshot',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
